package Algorithm.leetcode;

/*

    Given two strings s and t which consist of only lowercase letters.

            String t is generated by random shuffling string s and then add one
            more letter at a random position.

            Find the letter that was added in t.

            Example:

            Input: s = “abcd” t = “abcde”

            Output: e

            Explanation: ‘e’ is the letter that was added.
*/

public class _389 {
    public char findTheDifference(String s, String t) {
        int intone = 0;
        int inttwo = 0;//其实也可以只有一个int，然后先加完一组array后再减去另一组array
        for (char item1 : s.toCharArray()) intone += item1;
        for (char item2 : t.toCharArray()) inttwo += item2;
        return (char) (inttwo - intone);
    }

}
